language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run build
before_install:
  - 'npm i -g firebase-tools'
deploy:
  provider: script
  script: firebase deploy --token=${FIREBASE_TOKEN}
  skip_cleanup: true
  on:
    branch: master
